### ISSUE TITLE
Automatizovat generování PDF dávek a nahrávání do systému GLS

### ISSUE THREAD

**Issue by PetrDlouhy** [auto-mat/do-prace-na-kole#15]
Spouštět skripty generující PDF se štítky pro GLS na serveru v rámci celery.

Bylo by dobré napřed vyřešit #14, protože na tom zjistíme, co to obnáší.

Také je potřeba si dát pozor, abychom velikostí generovaného souboru neshodili instanci AWS, nebo abychom zbytečně nezvýšili velikost Docker souboru (a tím pádem nezvýšili dobu zřizování nové instance).

**Comment by timthelion** [comment]
To je snad hotový ne?
