### ISSUE TITLE
add package code to gls description string

### ISSUE THREAD

**Issue by timthelion** [auto-mat/do-prace-na-kole#168]

**Comment by timthelion** [comment]
@PetrDlouhy Já to nevím jak, zda se mi že ten popís nelze dělat pro každý balík zvlašť, poradíš mě? 

https://github.com/auto-mat/do-prace-na-kole/blob/d1ac0d579a09030d7126616ebf3daa948ded4134/apps/t_shirt_delivery/gls/generate_gls_pdf.py#L124

**Comment by PetrDlouhy** [comment]
@timthelion V sytému GLS online se u každé položky zadává buď že je to konstantní, nebo číslo soupce v CSV souboru. Tedy když změníš tohle
```
        "pinfo_const": "on",
        "pinfo": "Nezastihnete-li adresáta, volejte AutoMat: 212 240 666",
```
na něco takového:
```
        "pinfo": "10",
```
Tak by to mělo brát data z desátého sloupce.

Je to samozřejmě celé trochu křehké, protože se posílají requesty do jejich webového systému, takže jakákoliv změna může mít neočekávané následky.

**Comment by timthelion** [comment]
Maybe this is done? https://github.com/auto-mat/do-prace-na-kole/commit/8aed43911cb18edb1bec0c80a0d2ea754bce0794

Still needs testing
