### ISSUE TITLE
Přidat notifikace

### ISSUE THREAD

**Issue by PetrDlouhy** [auto-mat/do-prace-na-kole#17]

**Comment by timthelion** [comment]
Tak jsem zkusil:
 1. https://github.com/django-notifications/django-notifications ale jsem narazil na https://github.com/django-notifications/django-notifications/issues/243 a říkal jsem si, že zkusím ještě něco jiného.
 2. Zkusil jsem tohle https://github.com/v1k45/django-notify-x/issues, což vypadá takhle:
![notifications](https://user-images.githubusercontent.com/1391608/52880947-a1590580-3163-11e9-8544-00f0b203a094.png)
Ty tlačitka nejsou k níčemu připojené, musí se celý frontend dodělat. Taky nechapu ten jejich složité model.
3. Ještě jsem zkusil https://github.com/pinax/pinax-notifications ale nemá to smysl. Jen posílá emaily a nedělá to co chceme.
4. Ještě existuje https://github.com/django-wiki/django-nyt což je možná zajímavé, nevím ještě.
5. https://github.com/alireza-molaee/django-webline-notifications vypadá zajimavě, není udržované

**Comment by timthelion** [comment]
Done
