### ISSUE TITLE
Possibly incorrect text in change tshirt size regarding delivery dates

### ISSUE THREAD

**Issue by hartmmi1** [auto-mat/do-prace-na-kole#182]
Date and time: 15.4.2020, 11:50
URL:
https://dpnk.dopracenakole.cz/zmenit_triko/

Description: delivery dates state that delivery will be done from 21st of April to 27th of March, which seems weird considering March comes earlier in real life timeline.

Current state:
"Účastníkům zaregistrovaným do 15. dubna 2020 budeme trika i nákrčníky hromadně odesílat od 21. dubna 2020 do 27. března 2020. Jednoho dne pak na Vaši pracovní adresu zaklepe balík s triky pro všechny členy týmu."

Expected state:

Either:
"Účastníkům zaregistrovaným do 15. dubna 2020 budeme trika i nákrčníky hromadně odesílat od 21. dubna 2020 do 27. dubna 2020. Jednoho dne pak na Vaši pracovní adresu zaklepe balík s triky pro všechny členy týmu."

Or:

"Účastníkům zaregistrovaným do 15. dubna 2020 budeme trika i nákrčníky hromadně odesílat od 21. dubna 2020 do 27. května 2020. Jednoho dne pak na Vaši pracovní adresu zaklepe balík s triky pro všechny členy týmu."

**Comment by PetrDlouhy** [comment]
To špatně nastavil Ondra. Teď jsem to přenastavil: https://dpnk.dopracenakole.cz/admin/t_shirt_delivery/deliverybatchdeadline/?o=3

**Comment by timthelion** [comment]
Díky
