### ISSUE TITLE
Bylo by pěkné, kdybychom uměli hromadně vygereovat N voucherů daného typu

### ISSUE THREAD

**Issue by PetrDlouhy** [auto-mat/do-prace-na-kole#26]
Nejjednodušší řešení je přidat pole s počtem nově generovaných voucherů do typu voucheru.

**Comment by timthelion** [comment]
To není možné protože `CouponType` neobsahuje důležitá data jako procenta sleva. Můžeš teď ale importovat csvčka ve formě:

````
coupon_type,discount,receiver
FA,39,foo@bar.cz
FA,39,lol@baz.cz
FA,39,rar@mop.cz
FA,39,uf@lop.cz
FA,39,map@fop.cz
````

Počet řádků učí počet tvořených kuponů. `coupon_type` má být prefix `CouponType`u.

**Comment by PetrDlouhy** [comment]
@timthelion Myslím, že to stačí, dej to jen vědět Ondrovi.
