### ISSUE TITLE
django-smart-selects should be depricated

### ISSUE THREAD

**Issue by timthelion** [auto-mat/do-prace-na-kole#32]
https://github.com/digi604/django-smart-selects allows untrusted users to specify object managers https://github.com/digi604/django-smart-selects/blob/master/smart_selects/urls.py#L12 . This is dangerous.

**Comment by PetrDlouhy** [comment]
@timthelion #36 might be relevant to this. If we discover some simpler way to set/create team, it would simplify many things.
