### ISSUE TITLE
Need to set url_as_patern=False in sitetrees.py when using real URLs

### ISSUE THREAD

**Issue by timthelion** [auto-mat/do-prace-na-kole#45]
https://github.com/auto-mat/do-prace-na-kole/commit/51bde2eee1a3ef5c74842f5ed55129616fe778d4#diff-61e391286a6b784c20fd1c47450f684cR23

https://github.com/idlesign/django-sitetree/blob/master/sitetree/utils.py#L46

**Comment by timthelion** [comment]
https://github.com/auto-mat/do-prace-na-kole/commit/72f891679767872f408d132588d0e0f326a6924e

**Comment by PetrDlouhy** [comment]
To už by mělo být pullnuté v rámci PR Pipenv2, nebo ne?

**Comment by timthelion** [comment]
Jo, už to tam je.
