### ISSUE TITLE
Titul stranka se soutěžama je nesprávný

### ISSUE THREAD

**Issue by timthelion** [auto-mat/do-prace-na-kole#47]
![pravidelnost](https://user-images.githubusercontent.com/1391608/50599799-5b93f680-0eaf-11e9-906f-3518e8e251a9.png)

Nemělo by tam "Výsledky pravidelnostních a výkonnostních soutěží" ale jenom "Výsledky pravidelnostních soutěží"

**Comment by PetrDlouhy** [comment]
@timthelion To je schválně. Rozdělili jsme to (zatím, možná se to do hlavní soutěže ještě změní) na "Pravidelnostní soutěže", "Výkonnostní soutěže" a "Ostatní". Typy soutěží, které nebyli vypsané v Lednové výzvě jsem ale schoval z menu (v sitetree jsou jen vypnuté). Je potřeba se dohodnout s Ondrou a pokud se přeci jen vypíšou, tak to zase zapnout.
