### ISSUE TITLE
Enter v chained fieldu dělá blbosti

### ISSUE THREAD

**Issue by timthelion** [auto-mat/do-prace-na-kole#91]
![chained](https://user-images.githubusercontent.com/1391608/53953887-e7571880-40d4-11e9-9333-de73889cd72d.png)

Jestli dám Enter poté co zadám název společnosti, tak nemůžu vybrat ani vytvořit pobočku. Uživatele jsou zmatené.

**Comment by PetrDlouhy** [comment]
Jdu to teď řešit. Minulý rok myslím zčervenalo políčko kolem toho textu, letos jen trochu zčervená ten text.

Asi nechám ten text úplně zmizet, nebo něco a ještě zčervenám ten popis pod tím.
